package com.sfa.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 21 16:06:26 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppointmentTypeViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppointmentTypeViewImpl() {
    }
}

